monolog:
  handlers:
    main:
      type: rotating_file
      max_files: 10
      path: "%kernel.logs_dir%/%kernel.environment%-debug.log"
      level: debug
      channels: ["!event", "!doctrine", "!cache"]
    error:
      type: rotating_file
      max_files: 10
      path: "%kernel.logs_dir%/%kernel.environment%-error.log"
      level: error
      channels: ["!event", "!doctrine", "!cache"]
