name: $APP_NAME

services:
  init:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: init
    container_name: ${APP_NAME}-init
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
      - ./.docker/init/init.sh:/docker/init/init.sh
      - ./.docker/init/init.local.sh:/docker/init/init.local.sh
    command: ["/bin/bash", "/docker/init/init.local.sh"]

  php:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: php
    container_name: ${APP_NAME}-php
    depends_on:
      init:
        condition: service_completed_successfully
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
      - ./.docker/php/nginx.conf:/etc/nginx/sites-available/default
    ports:
      - "${NGINX_PORT_EXT}:8080"

  db:
    image: mysql:${MYSQL_SERVER_VERSION}
    container_name: ${APP_NAME}-db
    working_dir: /application
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_520_ci,
        --innodb-file-per-table=1,
        --local-infile=1,
      ]
    volumes:
      - database_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
    healthcheck:
      # The service is considered healthy when:
      # - connection to db can be established, and
      # - we can run a simple SQL query.
      test:
        [
          "CMD-SHELL",
          "mysql -h db -u$$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE -e 'SHOW TABLES;'",
        ]
      interval: 10s
      retries: 6
      start_period: 1m
      timeout: 3s
    ports:
      - "${DATABASE_PORT_EXTERNAL}:${MYSQL_PORT}"

  frontend:
    container_name: ${APP_NAME}-frontend
    image: node:latest
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend:rw
    command: bash -c "npm install; npm run dev;"
    user: 1000:1000
    ports:
      - "${FRONTEND_PORT_EXTERNAL}:5173"

  azure:
    image: ghcr.io/torqit/symfony-azure-provisioning:0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.azure/parameters.dev.json:/azure/parameters.dev.json:rw
      - ./.azure/parameters.prod.json:/azure/parameters.prod.json:rw
      - azure:/root/.azure

volumes:
  database_volume:
  azure:
