# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  env(DATABASE_URL): ''
  env(DEFAULT_URI): ''

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    azure_container_client:
      class: AzureOss\Storage\Blob\BlobContainerClient
      factory: ['App\Flysystem\BlobContainerClientFactory', 'createContainerClient']
      arguments:
        $connectionString: 'DefaultEndpointsProtocol=https;AccountName=%env(string:AZURE_STORAGE_ACCOUNT_NAME)%;AccountKey=%env(string:AZURE_STORAGE_ACCOUNT_KEY)%;EndpointSuffix=core.windows.net'
        $containerName: '%env(string:AZURE_STORAGE_ACCOUNT_CONTAINER)%'

    azure_adapter:
      class: 'AzureOss\FlysystemAzureBlobStorage\AzureBlobStorageAdapter'
      arguments:
        $containerClient: '@azure_container_client'
