name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ci__${{ github.ref }}
  cancel-in-progress: true

jobs:
  CI:
    uses: TorqIT/pimcore-github-actions-workflows/.github/workflows/ci-docker.yml@v0
    permissions:
      contents: read
      actions: read